version: 2
updates:
    # Maintain dependencies for Node
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'monthly'
      assignees:
          - 'mrcgrtz'
      groups:
          cssnano:
              patterns:
                  - 'cssnano*'

    # Check for updates to GitHub Actions
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      assignees:
          - 'mrcgrtz'
